### ISSUE TITLE
Add ability to navigate from one page object to another page object

### ISSUE THREAD

**Issue by davidmote** [Codebiosys/veripy#12]
Veripy needs to allow a user, via a sentence, to change the Page context of the currently running test. This will allow a test designer to correctly segregate the Page object information and move from one page object to another. 

## Actual Behavior
All page definitions for related pages are all placed in one page configuration. New context can only be achieved by using a Given statement that loads a fresh page via url.

## Expected (or Proposed) behavior
A user can navigate to a new page context via click, which changes the context for the remaining tests to the new page object.

## Steps to reproduce (if any)

N/A

## Tasks to complete (if multiple)

- [ ] Create new sentence for moving page contexts
- [ ] Add navigation to local test suite, and an additional page
- [ ] Create test that proves the navigation enables the new Page configuration, and disables the old Page configuration
