### ISSUE TITLE
Implement a sentence for logging in

### ISSUE THREAD

**Issue by m-martinez** [Codebiosys/veripy#18]
Currently, in order to log in, a series of Gherkin sentences must be written in order to interact with a login screen. A convenience sentence that covers most cases (username/password) should be provided in order to keep statements concise. The sentence should follow the format:

```gherkin
Given the user logged in via "Login Page" with username "someusername" and password "somepassword"
```

Where "Login Page" is a page fixture format file containing: 
* `username`: the field to use for logging in
* `password`: the field to use for password
* `submit`: the submit button

A potential short-coming is if the target login page has 2-Factory authentication enabled. 

### Module(s) Affected

N/A

## Actual Behavior

N/A

## Expected (or Proposed) behavior

The user can log in with a single sentence.

## Steps to reproduce (if any)

N/A

## Tasks to complete (if multiple)

- [ ] Implement sentence that can log into an application with the page fixture and credentials provided.
- [ ] Testing is updated
- [ ] Documentation is updated

## Screenshots (if applicable)

N/A
