### ISSUE TITLE
Implement sentence to invert another sentence

### ISSUE THREAD

**Issue by m-martinez** [Codebiosys/veripy#21]
Gherkin does not have a keyword to "invert" the asserting of a step. Instead it is left to the step library developer to supply steps for the inverse of assertions. This can lead to non-DRY step libraries where there will be one implementation for a step, and another one with slightly different logic for the inverse of the same step step. 

Example:

```Gherkin
Then it is not the case that the the "Phone Number" field is required
```

#### Drawbacks

Doing this may add unnecessary ambiguities to existing sentences as there now more than one way to achieve the same thing: 

```Gherkin
Then it is not the case that the the "Phone Number" field is not required
Then the "Phone Number" is required

# or, conversely

Then it is not the case that the the "Phone Number" field is required
Then the "Phone Number" is not required

```

### Module(s) Affected

N/A

## Actual Behavior

N/A

## Expected (or Proposed) behavior

N/A

## Steps to reproduce (if any)

N/A

## Tasks to complete (if multiple)

- [x] Implement a sentence that invert the sentence of any other sentence
- [x] Documentation is updated
- [x] Tests are updated

## Screenshots (if applicable)

N/A

**Comment by davidmote** [comment]
Sentence Added in v0.1.0
